@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NzkzMjAyMjF9.AtwpAmkLWkFZqghTS6I0-OmS2Fy22bNftlIieWwbd5s

POST {{url}}/afericoes
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idSensor" : "34",
    "unidade" : "Graus Celsius",
    "valor" : "26"
}

###
GET {{url}}/afericoes
Authorization:  Bearer {{token}}

###
PUT {{url}}/afericoes/1
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idSensor" : "34",
    "unidade" : "Graus Celsius",
    "valor" : "30"
}

###
GET {{url}}/afericoes/1
Authorization:  Bearer {{token}}

###
DELETE {{url}}/afericoes/1
Authorization:  Bearer {{token}}

###

POST {{url}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "query { afericoes { id idSensor unidade valor } }"
}

###
POST {{url}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "mutation { criarAfericao ( dados: { idSensor: \"T1\", unidade: \"Graus Celsius\", valor: \"26\" } ) {id idSensor unidade valor} }"
}

###

POST {{url}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "mutation { alterarAfericao ( id: 1, dados: { idSensor: \"T1\", unidade: \"Alteradoo\", valor: \"26\" } ) {id idSensor unidade valor} }"
}

###
